ALTER TABLE screens ADD COLUMN IF NOT EXISTS validation_regex TEXT;
ALTER TABLE screens ADD COLUMN IF NOT EXISTS max_length INTEGER;
ALTER TABLE screens ADD COLUMN IF NOT EXISTS max_retries INTEGER;
ALTER TABLE screens ADD COLUMN IF NOT EXISTS timeout_screen TEXT;
