[package]
name = "ussdframework"
version = "0.1.0"
edition = "2021"
authors = ["Rhaqim <anusiemj@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ussdframework"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
actix-web = "4.0"
chrono = { version = "0.4", features = ["serde"] }
config = "0.14.0"
lazy_static = "1.4.0"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }